# Generated by Django 4.2.7 on 2024-01-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coupon_coupon_code_cartitem'),
        ('core', '0002_rename_first_name_user_username_remove_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(related_name='user', to='main.cartitem'),
        ),
    ]
