# Generated by Django 4.2.7 on 2024-01-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon',
        ),
    ]
