# Generated by Django 4.2.7 on 2024-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_premium_plus_user_user_is_premium_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
