# Generated by Django 4.2.7 on 2024-02-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_coupon_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
