# Generated by Django 4.2.7 on 2024-01-20 12:06

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Clothing', 'clothing '), ('Electronics', 'electronics'), ('Food', 'food '), ('Home Services', 'home Services')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(help_text=' "9:00-23:00" or "around the clock".', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_company_images)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('discount_price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('about', models.TextField(blank=True, max_length=200)),
                ('expire_date', models.CharField(blank=True, help_text='enter date in following format day-month-year', max_length=25, null=True)),
                ('expire_time', models.CharField(blank=True, help_text='enter time in following format 12:00:00', max_length=25, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='main.company')),
            ],
        ),
    ]
