# Generated by Django 4.2.7 on 2024-01-18 13:19

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Clothing', 'clothing '), ('Electronics', 'electronics'), ('Food', 'food '), ('Home Services', 'home Services')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(help_text=' "9:00-23:00" or "open 24 Hours".', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_company_images)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('expire_date', models.DateField()),
                ('limit', models.DecimalField(decimal_places=0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='main.company')),
            ],
        ),
    ]
