# Generated by Django 4.2.7 on 2024-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_coupon_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
