# Generated by Django 4.2.7 on 2024-01-26 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_coupon_coupon_code_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ManyToManyField(related_name='claimed_coupon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limit',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
