# Generated by Django 4.2.7 on 2024-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_coupon_hot_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='hot_offer',
            field=models.BooleanField(default=False),
        ),
    ]
